// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0dfnm2CnqqM0ehMItujcIUzZt6_tfVeM',
    appId: '1:1002821305533:web:152c299344f9c6e23563d4',
    messagingSenderId: '1002821305533',
    projectId: 'stayeasy-a9904',
    authDomain: 'stayeasy-a9904.firebaseapp.com',
    storageBucket: 'stayeasy-a9904.firebasestorage.app',
    measurementId: 'G-4SZ822CNBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQm5BlNjNYh3aiQMN9OHTZSRsU3FPstms',
    appId: '1:1002821305533:android:59fe4133e710bb143563d4',
    messagingSenderId: '1002821305533',
    projectId: 'stayeasy-a9904',
    storageBucket: 'stayeasy-a9904.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6JgZSXVuR6lKkKeeyWThtG4yHQ2OkbcQ',
    appId: '1:1002821305533:ios:a31afd4ec13a0ab03563d4',
    messagingSenderId: '1002821305533',
    projectId: 'stayeasy-a9904',
    storageBucket: 'stayeasy-a9904.firebasestorage.app',
    iosClientId: '1002821305533-8ue7t0cpgd6a2d4g066uuk5t58l1o80o.apps.googleusercontent.com',
    iosBundleId: 'com.example.stayeasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6JgZSXVuR6lKkKeeyWThtG4yHQ2OkbcQ',
    appId: '1:1002821305533:ios:a31afd4ec13a0ab03563d4',
    messagingSenderId: '1002821305533',
    projectId: 'stayeasy-a9904',
    storageBucket: 'stayeasy-a9904.firebasestorage.app',
    iosClientId: '1002821305533-8ue7t0cpgd6a2d4g066uuk5t58l1o80o.apps.googleusercontent.com',
    iosBundleId: 'com.example.stayeasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0dfnm2CnqqM0ehMItujcIUzZt6_tfVeM',
    appId: '1:1002821305533:web:66db7c419f8eacd53563d4',
    messagingSenderId: '1002821305533',
    projectId: 'stayeasy-a9904',
    authDomain: 'stayeasy-a9904.firebaseapp.com',
    storageBucket: 'stayeasy-a9904.firebasestorage.app',
    measurementId: 'G-6G9ET7WGGD',
  );
}
